### ISSUE TITLE
Django RegexField field drops case insensitivity -- makes compiled object case sensitive

### ISSUE THREAD

**Issue by netvigator** [ambitioninc/django-regex-field#26]
I need case insensitivity (lack of case sensitive). I compile an object as case insensitive, and immediately afterwards, it works as case insensitive. I can store it in the database, and at that moment, it still works as case insensitive. But when I come back later, case insensitivity is LOST -- the compiled object is CASE SENSITIVE.

Real life example here:

https://stackoverflow.com/questions/49314431/django-regexfield-field-drops-case-insensitivity-makes-compiled-object-case-s

I posted there before I found this github place.

Looking at the database, I am guessing that the compiled object is not stored, rather what gets put in the table cell is the text expression that gets compiled.  Compiling an object takes some CPU ticks, I was hoping that the actual compiled object was stored, but it does not appear that way.  Please clarify, thanks.

**Comment by wesokes** [comment]
@netvigator I added a simple way to use regex flags in the field definition. This isn't able to store different regex flags per record, but it does let you specify regex flags per field. You can see an example in this pr.

https://github.com/ambitioninc/django-regex-field/pull/30/files

and also in the docs. It looks like I messed up the formatting on the docs, but you can still see the example.

**Comment by wesokes** [comment]
@netvigator to answer your question, no, the actual python regex object is not stored in the database, it is only the pattern stored as text.
